### ISSUE TITLE
EIP 3198 (BASEFEE)

### ISSUE THREAD

**Issue by DavePearce** [ConsenSys/evm-dafny#126]
_(this is a placeholder so we don't forget about this)_

It seems [EIP 3198](https://eips.ethereum.org/EIPS/eip-3198) introduced a bytecode call `BASEFEE` which is used in the reference test `GeneralStateTests/stExample/eip1559.json`.  This bytecode does not appear in the yellow paper!  So, I'm not really sure what to do with it yet.

**Comment by booleanfunction** [comment]
It would be useful to include the `BASEFEE` bytecode for the Dafny-zkEVM.

**Comment by hmijail** [comment]
From [another issue](https://github.com/ConsenSys/evm-dafny/issues/487#issuecomment-1345786026):
> While looking into this I noticed that the Berlin fork contains about 13K tests, London about 20K, and Paris/Merge about 21K.
So moving to a more current fork would give us over 30% more tests.
> 
> Moving to London would mean adding the BASEFEE opcode.
Moving to Paris/Merge would mean changing the DIFFICULTY opcode to PREVRANDAO.

**Comment by DavePearce** [comment]
subsumed by #526
