### ISSUE TITLE
Execution of the Precompiled Contracts and evaluation of their gas charge

### ISSUE THREAD

**Issue by MiladKetabGhale** [ConsenSys/evm-dafny#399]
According to YP (BERLIN VERSION 3078285 – 2022-07-13) section 8, and Appendix E, the precompiled contracts are semantically evaluated different from the rest of opcodes. Accordingly, usual opcodes are evaluated by the execution of the Xi (uppercase) function, whereas precompiled ones are evaluated by execution of different Xi functions each coming their a different index. For example evaluation of SHA256 is through the execution of Xi_sha256. Also the gas charge for them is different. 

Based on the above, I think when calling a precompiled contract, we should be executing a Xi function devised specifically for that precompiled contract. Currently upon calling a precompiled contract, we using the usual Xi function to evaluate it. The following is failing for example with an out-of-gas error:

[381] (tests/GeneralStateTests/stStaticCall/static_CallSha256_5.json,static_CallSha256_5_Berlin_0_0_0)

**Comment by DavePearce** [comment]
Closing this now as test `stStaticCall/static_CallSha256_5` appears to be passing now.
