### ISSUE TITLE
Add `ARCHITECTURE.md` file

### ISSUE THREAD

**Issue by DavePearce** [ConsenSys/evm-dafny#412]
Adding an architectural overview of the repositories organisation would be useful to help people understand how it all works overall.

**Comment by MiladKetabGhale** [comment]
I want to add the architecture picture to this repository. Recall we draw initially for the FM paper but decided to leave out in the final version. I can include an image and then in the Architecture.md specify a link to the image so that github knows where to find it. But I am hesitant of adding the image to the main directory (at the top-most level of evm-dafny repo), because it would not be a proper place. How about creating a new subdirectory, calling it Architecture and placing both the image and the picture in that subdirectory?

**Comment by MiladKetabGhale** [comment]
OK another interesting thing: aside from where to place the png file which is the image of the architecture, now there is something else to note. Wherever the image might be placed (which I think inside the resources subdirectory might be the best place), there has to be a link to specify in the .md file of the Architecture for the image. In my current branch, that link would be something tied with my branch (not the master repo). That link will not work after merging the branch with the master. Therefore, temporarily I will add a link to the image based on my current working branch, but before the pull request, use a link relative to the master evm-dafny repo. This way, you will have chances for visibly seeing how it looks before it is merged.

**Comment by MiladKetabGhale** [comment]
OK, the architecture is ready for merge. @DavePearce and @franck44 please have a look and let me know.

Note one more thing: I have played with addition of the architecture in a playground under my personal repository. Over there in the main branch of the playground, the image appears directly in the Architecture.md file. Here though only the link to it appears in blue. I believe once it is pushed to the master, the image should appear inside the Architecture.md, just like in my playground.

**Comment by DavePearce** [comment]
Hey Milad,

Ok a few quick comments:

- Normally the file name is all capitals (i.e. `ARCHTECTURE.md`) to be consistent with out files (e.g. `README.md` and `CONTRIBUTORS.md`)
- I agree having the image files in the top-level is not ideal.  I'd suggest creating a directory called `assets/` in which you put the images.  Other sensible names might be `docs`, `misc`, or even just `images`.

**Comment by franck44** [comment]
@MiladKetabGhale @DavePearce 
Personally I liked the stack diagram in the paper as it gives a feeling of what we intend to expose (API) and what we intend to hide. 
That may be a good time to re-organise the files too, and adopt a consistent naming (e.g. some files start with Capital letter, sone not). 
I think the tests (or proved programs) need to be re-organised too: some "proofs" are in "tests" which may be confusing ... 
We may have a separate issue for this re-factoring, and discuss how to approach it.

**Comment by DavePearce** [comment]
I made a suggestion in #430 for moving some files out of `util/` and into another directory (I suggested `core`).

> (e.g. some files start with Capital letter, sone not).

I would suggest file names are all lower case.  This helps distinguish them from the module names which are capitalised.  Otherwise, we would have the file `Int.dfy` which contains the `Int` module ... but also a bunch of other modules (e.g. `U256`).

I'm not sure what the Dafny style guide suggests though? Let me look.

**Comment by DavePearce** [comment]
For the stack diagram, we could use a table then instead of an image?  Anyway, just a thought.

**Comment by franck44** [comment]
> It doesn't really say much on this particular point.

no but they use PascalCase for file names.

**Comment by DavePearce** [comment]
> no but they use PascalCase for file names.

Well, we can do that if you prefer.  I just find it confusing to have two things (e.g. `Int.dfy` and `module Int`) which are different but have the same name.  Still, its not a big deal as already `int.dfy` and `module Int` are close.

**Comment by MiladKetabGhale** [comment]
> Hey Milad,
> 
> Ok a few quick comments:
> 
>     * Normally the file name is all capitals (i.e. `ARCHTECTURE.md`) to be consistent with out files (e.g. `README.md` and `CONTRIBUTORS.md`)
> 
>     * I agree having the image files in the top-level is not ideal.  I'd suggest creating a directory called `assets/` in which you put the images.  Other sensible names might be `docs`, `misc`, or even just `images`.  I see you put a copy in `resources/` and that would be a fine place as well.
> 
>     * I don't think its useful to describe the `.github/workflow` folder.  Its not really part of the system, but some meta stuff.
> 
>     * I don't think its necessary to describe the `LEGAL.md` or `README.md` or `CONTRIBUTORS.md` files, or indeed the `ARCHITECTURE.md` file itself.  They are self explanatory.
> 
>     * I would adjust the headings you've used.  Something like "Repository Architecture" => "Overview", and "DafnyEVM Source Files" => "Source Files" and "DafnyEVM Architecture" => "Architecture" seems better.
> 
> 
> For the discussion of source files, I think it would be helpful to try and give the feeling of the "stack" itself. At the moment, you've separate with the top-level stuff and then what's in `util/`. There are three essential levels of the stack. I would go from the high-level things down to the lowest level things.
> 
> In fact, I actually think (and our discussion from the paper made me think this) that it might be helpful to reorganise the files in the repository somewhat. At the moment, we have a bunch of files in `util` which probably don't belong there (e.g. `stack.dfy`, `storage.dfy`, etc)

I initially was aiming for the "stack" and leveling of modules as it appears in our paper. Then I decided to go for the actual organization of the repository. But sure we can switch back to how we have represented it in the paper.

**Comment by MiladKetabGhale** [comment]
> @MiladKetabGhale @DavePearce Personally I liked the stack diagram in the paper as it gives a feeling of what we intend to expose (API) and what we intend to hide. That may be a good time to re-organise the files too, and adopt a consistent naming (e.g. some files start with Capital letter, sone not). I think the tests (or proved programs) need to be re-organised too: some "proofs" are in "tests" which may be confusing ... We may have a separate issue for this re-factoring, and discuss how to approach it.

OK. I will rearrange things according to the decision made in the paper. Maybe while doing that, I rename files as you have suggested (but for now might just leave them as they are).

**Comment by MiladKetabGhale** [comment]
I applied the suggestion you made. Please let me know if there are improvement which we can make further.
