### ISSUE TITLE
Clarify/simplify `Push`

### ISSUE THREAD

**Issue by franck44** [ConsenSys/evm-dafny#448]
At the moment, there are several versions of `Push` in different modules:
- a `little helper` `Push(s: OKState, k: nat) : State` in module `EvmBerlin` which is a refinement of abstract module `EVM`, but `EVM` has no `Push` function. This `Push` is the one that is used in the `OpSem` and hence in `Execute`, and it itself calls `Bytecode.Push`. 
- the `Push(st: State, bytes: seq<u8>) : State` in module `Bytecode`. This one calls `State.Push` 
- `Push` in module `EvmState` that calls the `Stack.Push`
- `Push` in module `Stack`.

First problem is that the helper in `EvmBerlin` is available only for Berlin and not in the abstract module `EVM` which it should probably lives in.
Second is that the semantics of `Push` is not fully defined in `Bytecode`. The extraction of the value to push is done in `EvmBerlin`.

**Proposed re-factoring.**

1. Make the `Push(s: OKState, k: nat) : State` the entry point for `Bytecode.Push` and move it to the `Bytecode` module. (this includes altering the interface and using `IsExecuting()` instead of `OKState` which should be OK.
2. Make the `Push(st: State, bytes: seq<u8>) : State` in `Bytecode` a helper, `PushHelper`.

**Comment by franck44** [comment]
@DavePearce Any thoughts?

**Comment by franck44** [comment]
Actually, we may also rewrite `Push1`, ... `Pushk` to include the decoding of the operand which maybe simpler.

```dafny
/**
    * Push one byte onto stack.
    */
    function method Push1(st: State) : State
    requires !st.IsFailure() {
        //
        if st.Capacity() >= 1
        then
            var bytes := Code.Slice(s.evm.code, (s.evm.pc+1), 1);
            var k := bytes[0] as u256;
            st.Push(k).Skip(2)
        else
            State.INVALID
    }

    /**
     * Push two bytes onto stack.
     */
    function method Push2(st: State) : State
    requires !st.IsFailure() {
        //
        if st.Capacity() >= 1
        then
             var bytes := Code.Slice(s.evm.code, (s.evm.pc+1), 2);
             var k := Bytes.ReadUint16(bytes,0) as u256;
            st.Push(k).Skip(3)
        else
            State.INVALID
    }
...
```

**Comment by DavePearce** [comment]
> @DavePearce Any thoughts?

Well, the issue arises because there is a bytecode called `Push` and we have also have a stack abstraction which itself has a concept of pushing / popping.  The challenge you have is that you cannot replace `State.Push()` with `Bytecode.Push()`.  They are semantically different I don't believe you can merge them safely.  _However, I could be wrong on that!_

What you could do, perhaps, is change the name of the method `State.Push()` to be e.g. `State.Add()` or `State.PushBack()` or `State.StackPush()`.   That might eliminate the

**Comment by DavePearce** [comment]
Also, for `Push()` in `EvmBerlin` ... well that is a convenience method. It could perhaps be moved into `Bytecode` to replace `Push(st: State, bytes: seq<u8>)`.
