### ISSUE TITLE
Add formal proofs of bytecode optimisations.

### ISSUE THREAD

**Issue by franck44** [Consensys/evm-dafny#480]
There are some patterns in EVM bytecode that can optimised gas-wise.

Some examples are listed in [this MSc Thesis](https://fenix.tecnico.ulisboa.pt/cursos/mma/dissertacao/1691203502343808).

With our API we can formally prove that these optimisations are correct:
- they generate the same final state (upto the value of gas and PC)
- they consume strictly less gas.

Note that we can prove them given an arbitrary initial state (of course satisfying some constraints wrt stack size, gas etc).

**Comment by DavePearce** [comment]
I think an interesting question here is how many examples we want to put in this repository.  Every example extends the time it takes to verify the codebase and, hence, how long a merge request takes to complete.  Potentially, we might want to consider a secondary repository which includes a more extensive list of examples?  Or maybe not.

**Comment by franck44** [comment]
yeah, I think it is good to have examples. It helps to showcase what we can do with the semantics.
