### ISSUE TITLE
Postconditions for Bytecode Semantics?

### ISSUE THREAD

**Issue by DavePearce** [Consensys/evm-dafny#502]
Recently, with #490, postconditions have been added to most or all of the functions describing the semantics of individual bytecodes.  For example, this:

```Dafny
    function method Sub(st: State) : State
    requires st.IsExecuting() {
        //
        if st.Operands() >= 2
        then
            var lhs := st.Peek(0) as int;
            var rhs := st.Peek(1) as int;
            var res := (lhs - rhs) % TWO_256;
            st.Pop().Pop().Push(res as u256).Next()
        else
            State.INVALID(STACK_UNDERFLOW)
    }
```

Was changed to this:

```Dafny
    function method Sub(st: State): (st': State)
    requires st.IsExecuting()
    ensures st'.OK? || st' == INVALID(STACK_UNDERFLOW)
    ensures st'.OK? <==> st.Operands() >= 2
    ensures st'.OK? ==> st'.Operands() == st.Operands() - 1
    {
        //
        if st.Operands() >= 2
        then
            var lhs := st.Peek(0) as int;
            var rhs := st.Peek(1) as int;
            var res := (lhs - rhs) % TWO_256;
            st.Pop().Pop().Push(res as u256).Next()
        else
            State.INVALID(STACK_UNDERFLOW)
    }
```

In essence, postconditions (i.e. `ensures` clauses) have been added which attempt to clarify certain aspects of what the function does.

In this thread, I want to consider whether or not this is actually an improvement for our code base.  The essential argument is:

1. **(Not Specifications)** Postconditions like this are not necessary in Dafny (since this is a `function`).  They are not providing a specification for the `function`.  Rather, the `function` is its own specification (this is because `function`s are _interpreted_ in Dafny, which contrasts with `methods` which are _uninterpreted_).
  
3. **(Verification Aid)** One situation when an `ensures` clause on a `function` makes sense is when it is needed to verify the `function`, or some other piece of code using it (e.g. see [`Pow()`](https://github.com/ConsenSys/evm-dafny/blob/14928a6490b411d498a6913e825854927a7e3d0c/src/dafny/util/int.dfy#L129) for an example); 

5.  **(Key Properties)** Another situation when an `ensures` clause on a `function` makes sense is when an important property must be maintained which is not obvious from its body.  Hence, adding it as a postcondition helps us double check this is true (e.g. see [`Expand()`](https://github.com/ConsenSys/evm-dafny/blob/14928a6490b411d498a6913e825854927a7e3d0c/src/dafny/core/memory.dfy#L53) as an example).  

7. **(Readability)** In my opinion, unnecessary `ensures` clauses on a `function` hurt readability as we simply have more code to read and understand.  Furthermore, `ensures` clauses take expressions which are inherently flat and this can make them very difficult to read (see below for an example).  Finally, the readability issue is particularly acute for people who are not familiar with specifications (noting that such people are our primary audience).

Ok, with the rough outline in place, I'm going to provide some more detailed discussion with examples.  

## Key Properties

Looking at our example above, an interesting question is whether or not the additional `ensures` clauses capture important properties which are not obvious from the code base.  Consider this one:

```Dafny
    ensures st'.OK? <==> st.Operands() >= 2
```

To my mind, this is pretty obvious from the body of the function.  Similarly for this one:

```Dafny
    ensures st'.OK? ==> st'.Operands() == st.Operands() - 1
```

Again, this is reasonably obvious from the line `st.Pop().Pop().Push(res as u256).Next()`.  

Overall, neither of these `ensures` clauses add any value for me.

## Readability

The `Sub` example above is actually not too bad in terms of readability.  Many of the instructions are like this, however some are more problematic.  For example:

```Dafny
function method ReturnDataCopy(st: State): (st': State)
    requires st.IsExecuting()
    ensures st'.OK? || st' == INVALID(STACK_UNDERFLOW) || st' == INVALID(RETURNDATA_OVERFLOW)
    ensures st'.OK? <==> st.Operands() >= 3 &&
                        (st.Peek(1) as nat + st.Peek(2) as nat) <= st.evm.context.ReturnDataSize()
    ensures st'.OK? ==> st'.Operands() == st.Operands() - 3
    {
        //
        if st.Operands() >= 3
        then
            var m_loc := st.Peek(0) as nat;
            var d_loc := st.Peek(1) as nat;
            var len := st.Peek(2) as nat;
            if (d_loc + len) <= st.evm.context.ReturnDataSize()
            then
                // Slice bytes out of return data (with padding as needed)
                var data := st.evm.context.ReturnDataSlice(d_loc,len);
                // Sanity check
                assert |data| == len;
                // Copy slice into memory
                st.Expand(m_loc, len).Pop().Pop().Pop().Copy(m_loc,data).Next()
            else
                State.INVALID(RETURNDATA_OVERFLOW)
        else
            State.INVALID(STACK_UNDERFLOW)
    }
```

The `ensures` clauses are hard to understand because: (1) they are long and quite flat; (2) they use anonymous stack locations (e.g. `st.Peek(1) as nat`).  This contrasts with the body of the `function` which gives names to the locations in question (Ok, actually the names could be improved in this case I think, but the point remains).  In fact, I'm going to argue that adding this clause in particular is not improving our code base:

```Dafny
    ensures st'.OK? <==> st.Operands() >= 3 &&
                        (st.Peek(1) as nat + st.Peek(2) as nat) <= st.evm.context.ReturnDataSize()
```

In my opinion, this clause is not readable by anyone except an expert.  In fact, I could not read and understand this --- and I wrote the original version of the function!  I think the presentation in the body itself provides a much better and more readable description (esp if we improve the variable names and perhaps allow `st.Pop().Pop().Pop()` to be replaced with `st.Pop(3)`).

## Conclusion

Overall, I think this is an important discussion for us to have and (hopefully) find some agreement on.  Its not immediately obvious how best to use the various mechanisms that Dafny provides, and I think we want to eventually settle on some kind of accepted practice within the group at least.

**Comment by hmijail** [comment]
As a Dafny & FM beginner...
My current mental model is that I can look at the `requires` and `ensures` as a summary of the function/method and be done. The actual implementation is advanced magic I can typically ignore unless I really need it.

So, to me, the version with the `ensures` allows me to pick up what I need immediately, while the version without them does demand much more effort from me - at least that's how it feels in principle.

Surely anyone looking into Dafny for the first time will need some explanations. I feel even I could explain how to use the `requires` and `ensures`. I don't think I could do the same based on the function/method bodies. If you have to start mentioning how one of them is transparent/interpreted while the other isn't, IMHO you've already added a new layer of pain.

**Comment by DavePearce** [comment]
Hey,

I understand that highlighting key properties is useful.  But, more unnecessary things to read overall makes it harder to digest.  For example, I do not find this is easy to understand:

```Dafny
requires st.IsExecuting()
    ensures st'.OK? || st' == INVALID(STACK_UNDERFLOW) || st' == INVALID(RETURNDATA_OVERFLOW)
    ensures st'.OK? <==> st.Operands() >= 3 &&
                        (st.Peek(1) as nat + st.Peek(2) as nat) <= st.evm.context.ReturnDataSize()
    ensures st'.OK? ==> st'.Operands() == st.Operands() - 3
```

Anyway, its a stylistic issue so its hard to win an argument eitherway.

**Comment by DavePearce** [comment]
> IMHO you've already added a new layer of pain.

Just remember that I am not adding this pain --- it is an artifact of Dafny.  I agree trying to explain it is difficult though.

**Comment by hmijail** [comment]
Yes, but I'm guessing that users of our stuff probably don't really want to know too much about Dafny; they _"just"_ want a spec with the guarantees of mechanical verification, etc. 

And the spec is in the requires/ensures, right? All the rest is necessary and great to dig in, but if you can keep it under the hood, then even better.

I guess it's the same as publishing an interface and hiding the implementation, even if it's open source.

**Comment by DavePearce** [comment]
> And the spec is in the requires/ensures, right?

Actually, no.  The whole function is the spec.  That's what I am trying (and failing) to explain above.  This is a subtle aspect of languages like Dafny (and Whiley).  There is a fundamental difference between a `method` and `function` in this case.  If it were a `method` we had written, then yes the `ensures` would be the spec.  But, for a `function` (and, accepting the unfortunate Dafny syntax, a `function method`) its different.  

Anyways, I feel like I am losing this argument now.  But, for me, things like this go against everything I strive for as a programmer:

```Dafny
function method SelfDestruct(st: State): (st': State)
    requires st.IsExecuting()
    ensures st'.RETURNS? || st' == INVALID(STACK_UNDERFLOW) || st' == INVALID(WRITE_PROTECTION_VIOLATED)
    ensures st'.RETURNS? <==> st.Operands() >= 1 && st.WritesPermitted()
    ensures st'.RETURNS? ==> 
        var a := st.evm.context.address;
        a in st'.world.accounts 
        && st'.world.accounts[a] == st.evm.world.accounts[a].(balance := 0)
        && a in st'.substate.selfDestruct
    ensures st' == INVALID(STACK_UNDERFLOW) <==> st.Operands() < 1
    ensures st' == INVALID(WRITE_PROTECTION_VIOLATED) <==> st.Operands() >= 1 && !st.WritesPermitted()
   ...
```

If we keep with the idea of including postconditions, then we will have to find ways to make them more comprehensible.

**Comment by franck44** [comment]
I think the `requires/ensures` are necessary for the specs. They provide 

- information that is not obvious in the body
- properties that are checked (so if we make a mistake/optimisation in the body, we still check that post conditions are satisfied).
- [and the pre/post conditions do not impact the Java/Go generated code as they are discarded in code generation.]

I don't think it matters whether you use a `method` or a `function method` (and recursion) to write the code, you can add a `relational` spec in the form of pre/post conditions (the post conditions capture relations between the input and the output).
The body (imperative or functional) is how the result is computed, not what is should satisfy.

As I said before, I think this is an essential feature of Dafny. If we use only the body (without pre/post) the spec could be written in any other language, we do not add anything.
IMHO it is a great feature that provides some insight into the result of a computation (e.g. exactly when it returns an `State.INVALID` state etc).

**Comment by DavePearce** [comment]
> information that is not obvious in the body

Well, the question is how do we decide what should be in the `ensures` clauses, and what should not.  What is the "style guide" here?  For example, in the `SelfDestruct`, some information is included but not all.  What's the decision making process here?

I would also say that the `ensures` clauses go beyond information that is not obvious in the body.  For example, the change in stack delta is obvious from the body.  However, one might argue that the presence of an account on the self destruct list is not obvious.

> I don't think it matters whether you use a method or a function method

Did you mean "function or function method" here?  Using a `method` to implement our semantics would have quite big consequences.  It would mean a whole lot of our current tests would fail to verify, for example.

> The body (imperative or functional) is how the result is computed, not what it should satisfy.

That is not correct in this case.  Every single piece of code in our DafnyEVM is part of the specification.  There is no imperative code that is hidden behind a spec.  That is the whole point of what we are doing.

> As I said before, I think this is an essential feature of Dafny. If we use only the body (without pre/post) the spec could be written in any other language.

That is also not correct.  We can verify code using functions in Dafny regardless of whether they have `ensures` clauses.  The purpose of the `ensures` clauses is for presentation and to allow us to check key properties of interest.

> IMHO it is a great feature that provides some insight into the result of a computation

It is a great feature when it conveys information clearly.
