### ISSUE TITLE
Refactor `EvmState.State`

### ISSUE THREAD

**Issue by DavePearce** [ConsenSys/evm-dafny#511]
This structure has been a bone of contention since the beginning.  It is confusing because it wraps several things together: (1) the executing VM state; (2) the various return types (e.g. `RETURNS`, `REVERTS`, `INVALID` for a contract call / creation; (3) continuations for the various `CALL` and `CREATE` bytecodes.  However, there is also some elegance in how it works that would be lost with a refactoring.  Despite the above, I think it makes sense to try and split out the various things it is doing.

Currently, it looks like this:

```Dafny
datatype State =
          OK(evm:T)
        | CALLS(evm:T,
                sender: u160,        // sender
                ...
        | CREATES(evm:T,
            gas: nat,            // available gas for creation
            endowment: u256,     // endowment
            initcode: seq<u8>,  // initialisation code
            salt: Option<u256>  // optional salt
        )
        | INVALID(Error)
        | RETURNS(gas:nat,data:seq<u8>,world: WorldState.T,substate:SubState.T)
        | REVERTS(gas:nat,data:seq<u8>)
```

In this way, the semantics of bytecodes is then e.g. `function method Return(st: State): (st': State)`.

Instead, I would suggest a top-level structure of:

```Dafny
// Possible states after execution
datatype State = Return | Continuation

// Possible ways a contract call/create can terminate
datatype Return = INVALID(Error)
        | RETURNS(gas:nat,data:seq<u8>,world: WorldState.T,substate:SubState.T)
        | REVERTS(gas:nat,data:seq<u8>)

// Mechanism for breaking contract call / creations into continuations.
datatype Continuation = 
        | CALLS(evm:T,
                sender: u160,        // sender
                ...
        | CREATES(evm:T,
            gas: nat,            // available gas for creation
            endowment: u256,     // endowment
            initcode: seq<u8>,  // initialisation code
            salt: Option<u256>  // optional salt
        )
```

Observe that the `Ok(evm)` case has gone entirely.  Thus, the semantics for bytecodes would be written e.g. `function method Return(evm: EVM): (st: State)`.

**Comment by DavePearce** [comment]
To be fair, there is at least one other option which makes sense.  Something like this:

```
// Possible states after execution
datatype State = Execution | Return | Continuation

datatype Execution = Ok(evm:T)
...

type ExecutingState = st:State | st.Execution?
type ReturningState = st:State | st.Return?
type ContinuingState = st:State | st.Continuation?
```

**Comment by franck44** [comment]
At some stage, there was an `OKState` that was used in the `bytecode.dfy` file:
```
function method Add(st: OKState): State
...
```
and no `requires IsExecuting`.

**Comment by DavePearce** [comment]
> At some stage, there was an OKState that was used in the bytecode.dfy file

Yeah, so I would suggest bringing that back and just renaming it to be `ExecutingState` to avoid ambiguity.
