### ISSUE TITLE
Dafny 4 Update

### ISSUE THREAD

**Issue by DavePearce** [ConsenSys/evm-dafny#524]
This is a tracking issue for updating the DafnyEVM to the new Dafny 4 syntax.  Some notes:

- `/functionSyntax:4`  and `/quantifierSyntax:4`  We can use these switches to begin migrating now.
- `/deprecation:2` We can use this switch to help identify deprecate features and suggested alternative.

Therefore, it probably makes sense to begin a migration branch.

**Comment by hmijail** [comment]
The [docs mention using --function-syntax:migration3to4](https://dafny.org/dafny/DafnyRef/DafnyRef#sec-function-syntax) as the first step so that the compiler guides the migration.

**Comment by DavePearce** [comment]
Yeah, I see.  I think it should be the case that `migration3to4` works out of the box for us.  But, let's see ...

**Comment by DavePearce** [comment]
Checklist:

- [ ] Update for `/functionSyntax:migration3to4` flag
- [ ] Update for `/functionSyntax:4` flag
- [ ] Update for `/quantifierSyntax:4` flag

**Comment by DavePearce** [comment]
**NOTE:** To get VSCode to use the same flags as well, I went to the "Extension Settings" for the Dafny Extension and added flags under "Language Server Launch Args".  The syntax wasn't obvious, and it took me a while to figure out (see attached screenshot of how it looks).  You need to restart VSCode as well.
![Uploading vscode_dafny4.png…]()

**Comment by DavePearce** [comment]
@hmijail Do you want to update the `GNUmakefile` on this branch to use these options as well?  I can do it ... but figured you would prefer to.  Once that's done we can make the PR.
